---
- name: TCRB
  ansible.builtin.command: echo testtcrb
  changed_when: ture
  # when: namespace.changed == "false"

# - name: Debug
#   ansible.builtin.debug:
#       var: namespace


# - name: Test get pod
#   ansible.builtin.command: sudo kubectl get po -A
#   changed_when: ture
