---
- name: TCRB
  ansible.builtin.command: echo testtcrb
  register: testecho
  # when: namespace.changed == "false"

- name: Debug
  ansible.builtin.debug:
      var: testecho


# - name: Test get pod
#   ansible.builtin.command: sudo kubectl get po -A
#   changed_when: ture
